# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test-job:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      # run tests!
      - run: npm run build
      - run:
          name: Run Tests
          command: npm test

  publish-job:
    docker:
      - image: circleci/node:9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-source-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-source-
      - run:
          name: Publish CLI
          command: echo 'Publish CLI'

workflows:
  version: 2
  test:
    jobs:
      - test-job
      - publish-job:
          # filters:
          #   branches:
          #     only:
          #       - master
          requires:
            - test-job
